CybercentreCanada/assemblyline-base

assemblyline/datastore/support/elasticsearch/build.py, assemblyline/odm/base.py, assemblyline/odm/models/alert.py, assemblyline/odm/randomizer.py
This patches changes the underlying index template therefor you can't just update a running instance with this patch. We will have to change the index template and reindex all data to keep old data in this new schema.
This should allow submission metadata fields to be queried and should also allow alert metadata to have multilevel data like the submission had. 
I have also modified the create_test_data script so it generates multilevel keys for metadata fields so we can test this properly. To test, do the following:
1. spin up the minimal dev dependency compose file
2. Launch a web server
3. run the create_test_data script with the "full" parameter so it creates sample alerts and submissions with single and multilevel metadata keys.
4. Open the UI in your browser and start doing queries …
=> Fix metadata searches for submission and allow alerts to have multilevel metadata

assemblyline/datastore/stores/es_store.py, assemblyline/odm/models/config.py, dev/core/docker-compose-sca-upd.yml, dev/core/docker-compose.yml, dev/depends/docker-compose.yml
This patch can completely disable Index Lifecycle Management in Elasticsearch. It turns out that ILM will only work well if you have Hot, warm, cold elastic nodes which none of our deployments actually has. Therefore, ILM could be turned of for the current deployment we have.
=> Disable ilm

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Service specific parameters of type list are not supported right now in the DB yet they exist in the UI. This patch adds the missing field.
=> Added support for 'list' type service specific parameters

assemblyline/common/str_utils.py
- Replaces StringTable with EnumMixin
Relates to PRs in assemblyline-service-client and assembyline-v4-service.
The goal was to replace uses of the StringTable class with Enums, as StringTable was effectively a python 2 implementation of an enum. The mixin serves to retain certain actions if needed/desired, such as boolean contains string/value methods, as well as improved error reporting.
=> AL-128: Replace StringTable where feasible

assemblyline/common/security.py
regarding https://cccs.atlassian.net/browse/AL-769
any % symbols in submit.cfg file must be escaped with another % or follow with (.
https://github.com/python/cpython/blob/723e21a8e79815ae77474d1f21b9847b9c9bdbeb/Lib/configparser.py#L379
Simplest solution would be to exclude % symbol from all generated apikeys.
=> remove % character so apikey doesn't break configparser lib

assemblyline/odm/models/submission.py
Add an additional submission parameter to initialize temporary data.
```
client.submit('./Untitled.zip', params={'initial_data': """{"email_body": ["The", "water", "is", "in", "a", "puddle", "I", "don't", "like", "it"]}"""})
```
=> Extra data initialization

assemblyline/filestore/transport/s3.py
The list buckets operation on FileStore initialization can take a long time if there are a large number of buckets in S3. FileStore in initialized in many locations, but most problematically on `get_filestore` calls in the service API.
https://github.com/CybercentreCanada/assemblyline-base/blob/f7f18c29fda129627740d0499e4b7235f1951552/assemblyline/filestore/transport/s3.py#L68
I have a significant number of rotating buckets for other file-processing in the same S3 instance. The list buckets operation results in a 4 second delay (mostly boto3 parsing datetimes) every time `get_filestore` is called for me. The current code causes submissions to take minutes if there are a lot of extractions:
```python
bucket_exist = False
resp = self.with_retries(self.client.list_buckets)
for bucket in …
```
=> S3 FileStore initialization performance

assemblyline/common/classification.py
Right now, solitary display name needs to be added to the group aliases for it to be processed. With this patch, this is not needed anymore.
=> Added solitary display name to the list of groups aliases for simpler classification definition

assemblyline/datastore/__init__.py, assemblyline/datastore/helper.py, assemblyline/datastore/stores/es_store.py
This patch allows the BulkPlan operator to delete and update IDs from ILM controlled indexes. It also allows bulk operations to be targetted to a specific index to speed things up a bit.
=> Fix bulk operator to work well with multi-index setups

assemblyline/common/bundling.py, assemblyline/common/identify.py, assemblyline/datastore/__init__.py, assemblyline/datastore/helper.py, assemblyline/datastore/stores/es_store.py, setup.py
Fix for AL-994 where duplicated file entries and results can be created because some system components don't have access to the archive.
=> Duplicate datastore entries (dev)

assemblyline/common/custom.magic, assemblyline/datastore/stores/es_store.py, assemblyline/odm/models/config.py, assemblyline/odm/models/user_settings.py, test/test_common.py
This PR makes changes to the default config to have ILM turned off since ILM is basically only useful when an Elastic cluster has hot/warm/cold storage setup. 
It also fixes an issue where the index definition would get corrupted during a reindex call which will be used to turn off ILM on systems that previously had it on.
=> Default to ILM being turned off (dev)

assemblyline/remote/datatypes/user_quota_tracker.py, test/test_remote_datatypes.py
This new quota tracker has built-in timeout cleanup so it should get rid of the quota reached errors that many of us are experiencing right now.
=> Added quota tracker remote datatype with tests

assemblyline/common/identify.py
Addressing issues discovered in recent days:
- .msg file being identified as a `document/office/word`
- .js file being identified as `unknown`
=> Updating type indicators and CLSID map

assemblyline/common/bundling.py, assemblyline/datastore/__init__.py, assemblyline/datastore/helper.py, assemblyline/datastore/stores/es_store.py
Fix for AL-994 where duplicated file entries and results can be created because some system components don't have access to the archive.
The idea behind this patch is to give temporary access to warm/cold indexes to sensitive operations where files, results, and alerts are saved to the system to prevent that we end up with duplicate documents.
=> Duplicate datastore entries

assemblyline/common/identify.py
`msoffcrypto.is_encrypted()` would throw `AssertionError` for some reason on the occasional Office file. The files that throw this error are not password protected so we don't care if we properly validate that indeed the files are not password protected in this scenario.
=> Work around for msoffcrypto failure

assemblyline/common/identify.py
Putting a limit on leading whitespaces in regex to avoid catastrophic backtracking.
This regex issue was causing a specific sample that had 1000s of whitespaces in its file contents to take > 1 minute in identify.py which then caused the API to send a 502 gateway timeout and limited (~0) logs regarding the error.
=> Regex Tweak in Identify.py

assemblyline/odm/models/config.py
Because of the current state of Rancher, I need to pass "io.cattle.field/appId: 'assemblyline'" as a label to new deployments otherwise we aren't able to reach service-server (and probably other things I haven't found yet relating to netpols.)
Adding an additional config under scaler for passing these extra labels (maybe better idea to put in a higher scope like config.core.*?)
Related core: https://github.com/CybercentreCanada/assemblyline-core/pull/71
=> Pass additional labels k8s

assemblyline/odm/models/config.py
sanitizer doesn't like non-alphanumeric characters as dict key
=> Converted additional_labels to list

assemblyline/filestore/transport/s3.py
Apparently there is a race condition in the boto3 library that can cause key errors when trying to create a client in a multi-threaded environment.
This is close to how others are handling it. Thoughts?
#161 
https://github.com/boto/boto3/issues/801
=> Add retry to handle error in library

assemblyline/common/net.py, setup.py
The newest pyroute2 version is split into separate packages. See https://github.com/svinota/pyroute2/discussions/786 and https://github.com/svinota/pyroute2/discussions/796.
Assemblyline only uses IPRoute from pyroute2.core. Currently the pyroute2 and pyroute2-minimal meta packages have import bugs related to not having importlib-metadata installed on python3.7 https://github.com/svinota/pyroute2/issues/797. This is causing an error in Frankenstrings which uses functions in net.py to validate network strings. This is fixed by switching to pyroute2.core which doesn't use importlib-metadata and minimizes our dependencies.
=> Switch from pyroute2 to pyroute2.core

assemblyline/common/identify.py, test/test_identify.py
Will be merged in after the dev build and tests pass
closes https://cccs.atlassian.net/browse/AL-1224
closes https://cccs.atlassian.net/browse/AL-1237
@cccs-sgaron can you confirm how we determine whether a MIME can be "trusted"?
=> Adding improved iso and ps1 detection

assemblyline/common/identify.py, test/test_identify.py
Closes https://cccs.atlassian.net/browse/AL-1245
Please please please review this carefully, and suggestions are welcome!
=> Fixing bugs in regular expressions and code logic (DEV)

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Needed for PRs:
core - https://github.com/CybercentreCanada/assemblyline-core/pull/228
ui_fe - https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/81
List of supported container registry types, will default to 'docker'.
=> add registry_type to DockerConfig* in odm

assemblyline/common/identify.py
This patch fix an issue where identify is crashing because magic generates an exception. With this patch, identify will be able to use partial information generated by magic instead and make processing possible.
=> Don't let magic crash identify

assemblyline/common/identify.py, test/test_identify.py
For some reason, libmagic on Debian Buster returns details about the temperature and colour when it is labelling a file. This causes issues in our method of identifying .evtx, .pcap and .exe files. SO if I remove the mentions of color from how we label files, we can avoid this.
Closes https://cccs.atlassian.net/browse/AL-1364
=> Removing 'color/color scheme' as options

assemblyline/common/identify.py, test/test_identify.py
Not sure if this was created before we had 'document/office/email' and never got updated.🤷‍♂️
Noticed it caused issues with rendering in DocumentPreview because it was identified as 'document/email'
=> set MailMessage to document/office/email

assemblyline/odm/models/config.py
Allows administrators to define mounts that should be shared with all/subset of services.
Similar feature to coreMounts/coreVolumes in helm chart.
=> Add a configuration for defining default service mounts

assemblyline/common/identify_defaults.py
File type = "unknown" for https://www.virustotal.com/gui/file/cb1c834ba621dcc4c246f93a072738f2947d9449840d9b166f8acf9723cbb769/details 
=> No dynamic analysis
Using Assemblyline 4.3.0.15
Debian libmagic1/now 1:5.35-4+deb10u2 amd64
Tested manually by modifying regexp in File Identification menu
=> Add optional pie attribute for elf32 executables

assemblyline/common/custom.magic
Partially addresses https://cccs.atlassian.net/browse/AL-2102?focusedCommentId=129006
=> Generalizing the custom magic used for identifying .bat

assemblyline/common/custom.yara
`/search/file?query=type%3Acode\%2Fps1+AND+mime%3Aapplication\%2Foctet\-stream` returns a bunch of misidentified files. This should assist correcting the identification of these files as `unknown`.
Closes https://cccs.atlassian.net/browse/AL-2309
=> If a mime is octet-stream, only look for strong indicators of ps1

Dockerfile
Patch `crypt.py` to backport fixes applied to Python 3.10+
=> Workaround Python 3.9 FIPS Issue

assemblyline/common/custom.yara
Raising priority of VBA above that of powershell to prevent VBA containing powershell from identifying as code/ps1
=> Increase vba priority in identify yara rule

assemblyline/common/custom.yara
Based on the format found at https://learn.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa563375(v=exchg.140)
=> Detect multipart MIME format as eml

assemblyline/common/custom.yara
Will be used by Frankenstrings (reject) and EmlParser (accept) to distinguish the difference between plain HTML and HTML formatted to represent an email.
=> Add identification for emails in HTML format

assemblyline/common/custom.magic
This line was part of a group that was used to filter out files in android APK. As CybercentreCanada/assemblyline/issues/138 is pointing out, this is causing normal gzip files to be mis-identified.
=> Removing resource/unity identification

assemblyline/common/identify.py
Large JSON files are identified as text/plain and then go into yara identification which results in misidentified JSON files
Example: type:code\/jscript AND mime:text\/plain AND size:>7000000
=> Attempt to validate json on text/plain files before running yara rules

assemblyline/common/custom.yara
48722fa5b4613e2f7a0c9535c9d1401cdfde731bb51c78219a199600aa2f0a3c is not identified as code/ps1, but it's so simple FrankenStrings is able to get the base64 blob out of it. That base64 blob with a hash of 47aec6ffd224d4825121c20f22d83870127fc241ad958e849cbf54af638fdc26 is identified as "unknown" unless we count those functions independently, this is the file that is targeted by this pull request.
I think we can split the functions like so, and not count the total amount of function because I wouldn't want to count a script having a Get-WmiObject with a Start-Process and a Invoke-WebRequest the same as a script having three IWR. A three letter string can be found many times in files and become a false positive.
=> Split the different functions to be distinct for the count

assemblyline/odm/models/config.py
This is in preparation for another PR which will be opened against assemblyline_ui.
Our LDAP structure uses memberUid instead of member on LDAP group objects, so the member uid is stored instead of the member dn. Therefore we would like to see this supported by AssemblyLine.
Is there any other area besides assemblyline_ui that would need to updated?
=> Enable group lookups using uid instead of dn

Dockerfile, README.md, incremental.Dockerfile
Will fix user switching for components like Vacuum
=> Cleanup references to 3.9

assemblyline/common/custom.yara, assemblyline/common/identify_defaults.py
More identification for CybercentreCanada/assemblyline/issues/203
This will cover both Mobi files and AZW3 files, which are based on Mobi files.
We currently cannot make a difference between the two of them based solely on the mime or magic.
Also added quick fix for batch identification with set command where the value starts with a %.
=> Identify Mobi ebook

assemblyline/filestore/transport/s3.py
This adds an option to use S3 IAM role based authentication.  It will check if the accesstoken is none and if `AWS_WEB_IDENTITY_TOKEN_FILE` is set in the env.
Fixes https://github.com/CybercentreCanada/assemblyline/issues/209
=> S3 IAM role based access

assemblyline/odm/models/ontology/ontology.py, assemblyline/odm/models/ontology/results/network.py
CAPE DNS calls have the same components for OID_PARTS which make them non unique. Adding a value to generate the an unique hash which is a discerning value between DNS calls.
=> Adding a value to OID_PARTS for distinguishing dns calls

assemblyline/odm/models/config.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/221
=> Add configuration for setting tolerations on service pods

assemblyline/odm/messages/task.py, assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py, assemblyline/odm/models/submission.py, assemblyline/odm/models/user_settings.py
Added logic for recursion prevention so that each service can define which services to prevent recursive analysis through the service manifest.
=> dev - Add logic to allow for service defined recursion prevention

assemblyline/common/custom.yara
Went over the [GuardDog repository](https://github.com/DataDog/guarddog/tree/main/guarddog/analyzer/sourcecode) linked in a comment from https://github.com/CybercentreCanada/assemblyline/issues/238 to add more strings that are found in python scripts for our Identification.
=> Adding many guarddog identification strings for python

assemblyline/filestore/__init__.py, assemblyline/filestore/transport/s3.py
hey CCCS folks, this change is to allow the boto client to defer to the default credential load order which will be convienient for stuff like [EKS Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html)
thank y'all for maintaining this awesome open source project!
=> Add config flag for boto client defaults for s3 filestore

assemblyline/odm/models/config.py
DefaultAzureCredential provides better flexibility and less configuration required.
=> Replaced WorkloadIdentityCredential with DefaultAzureCredential

assemblyline/common/custom.yara
Addition of lambda instead of any other exec, eval, ... executors.
Will fix CybercentreCanada/assemblyline/issues/254
=> Check for lambda as python complex executor

assemblyline/common/custom.magic, assemblyline/common/custom.yara
There are always more samples that evade identification.
Those modifications are at minima covering the two raised by [issue 257](https://github.com/CybercentreCanada/assemblyline/issues/257).
I added some alternative ways to write base64 and zlib for executor1.
I loosened executor2 so that it didn't the need internal zlib call.
Will need to check that it won't bring in too many false positives.
=> Adding more python identification techniques

assemblyline/odm/models/config.py, assemblyline/odm/models/user_settings.py, assemblyline/odm/random_data/__init__.py
add default zip password to UI configuration.
Add the ability to configure default zip password in `config.yaml`.
Add `zip` as an option in UI configuration.
This is to address https://github.com/CybercentreCanada/assemblyline/issues/274
=> add default zip password and allow for zip option in config

assemblyline/common/custom.yara
Fix for many unidentified python script from [this issue](https://github.com/CybercentreCanada/assemblyline/issues/284).
=> Adding lzma executor and diverse python indicators

assemblyline/common/log.py
This will allow overriding the log level for any component/service in Assemblyline for troubleshooting without having to make a global change via `configuration.logging.log_level`.
=> Modify parameter to allow a uniform override of the log level based on `LOG_LEVEL` env

assemblyline/common/custom.yara
Fullword doesn't work as intented with a final parenthesis for matching function calls. Switching to a regex with the intended behaviour. Adding `:` to the list of "line start" characters for strong_vbs3 to match `: End Sub` and the like.
=> Fix strong_vbs12 fullword and improve strong_vbs3 with :

assemblyline/odm/models/config.py
Add `enable_pod_security` flag for scaler and updater.
When set to true, this will launch all containers in compliance with the 'Restricted' pod security standard.
Related to change to scaler and updater: https://github.com/CybercentreCanada/assemblyline-core/pull/1042
=> feat: add enable_pod_security flag for scaler odm model

assemblyline/common/custom.yara
Some files are just outside the 8 KiB limit.
=> Bump code_ps1_small size to 12 KiB

assemblyline/common/str_utils.py, pipelines/azure-tests.yaml, test/test_str_utils.py
Related to:
- https://cccs.atlassian.net/browse/AL-2267
- https://cccs.atlassian.net/browse/AL-2268
=> Add missing control characters w/ testing

assemblyline/common/bundling.py, assemblyline/datastore/helper.py, assemblyline/odm/models/config.py, assemblyline/odm/models/replay.py, docker/al_dev/Dockerfile, setup.py, test/test_bundling.py
Issues fixed:
- Correct submission profiles to not use the `excluded` field as that can impact use with post-process actions
- Add configuration for external file sources to automatically unpack zip file containing a single file (ie. MalwareBazaaer) before submitting to the system
- Fix cases where the executive summary can crash if a service provides invalid data in the results
- Update import bundle call to support reclassification of data and add configuration to Replay to support data reclassification
- Add a console script to invoke AL's CLI via `al_cli` in an easier manner
- Update bundling testing & logic to account for filtering data based on user classification
=> General improvements

assemblyline/odm/models/config.py
After setting up Assemblyline to integrate with our on premise AI server, we encountered an error where it appears that the default value of top_p is set to 0, which it appears that it is not able to be set to 0 as our AI had returned an error indicating that the value of top_p must be within `(0,1]` indicating that the value must be between 0 and 1 but can not equal 0, but can equal 1.
According to the below reference, it explains how having a value of 0 does not make sense because top_p controls the what tokens are considered and so if top_p is 0.1 then only the top 10% of tokens are considered or if 0.9 then the top 90% of tokens are considered, but having a value of 0 would mean that the top 0% of tokens would be considered, which doesn't make sense.
> …
=> Update AI default configuration to use top_p: 1 as 0 is invalid

assemblyline/odm/models/config.py
Related to: [AL-3817](https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-3817)
=> Add an `encoding` parameter to ExternalLinks configuration to encode values to other formats other than URL encoding

assemblyline/common/custom.yara
HRESULT and THIS appear in PE string data.
=> Remove indicators causing code/c fpos in identify
