assemblyline/common/constants.py, assemblyline/common/identify.py
https://cccs.atlassian.net/browse/AL-318
Addressing improved identification for .js and .html files
https://cccs.atlassian.net/browse/AL-23
Addressing identification for .ps1 (PowerShell) files
=> Improved Identification for .js/.html/.ps1 files

assemblyline/common/tag_whitelist.yml
added domains and URIs to whitelist per comments in AL-327
=> AL-327 - add domain to global whitelist

assemblyline/odm/models/result.py
test by following https://github.com/CybercentreCanada/assemblyline4_docs/blob/dev_setup_infra/docs/developer_manual/infrastructure/remote_development.md as well as pulling the other PRs for AL-243 from the other repos (ui, v4-service)
=> AL-243: Added table as a result section option

assemblyline/odm/models/result.py
test by following https://github.com/CybercentreCanada/assemblyline4_docs/blob/dev_setup_infra/docs/developer_manual/infrastructure/remote_development.md as well as pulling the other PRs for AL-248 from the other repos (v4-service, ui)
=> Initial commit for adding nested process cards as a result section

assemblyline/common/constants.py, assemblyline/common/identify.py
https://cccs.atlassian.net/browse/AL-455
=> Added functionality to identify .hta files

assemblyline/common/identify.py
Added the tag_to_extension key for .chm files
=> Added chm tag to extension

assemblyline/common/identify.py
- also removed a pattern from Java that is shared with ps1 files
- sample used is the ps1 file found here: https://cccs.atlassian.net/browse/AL-322
=> Added more cmdlets and classes to ps1 patterns

assemblyline/common/exceptions.py, test/test_exceptions.py
Changes in inspect between python2/3 broke the Chain decorators
=> Fix Chain and ChainAll decorators

assemblyline/common/exceptions.py, assemblyline/filestore/transport/s3.py, test/test_exceptions.py
The Chain and ChainAll decorators did not work right, fixed them and adjusted something related.
=> S3 exception bug

assemblyline/common/str_utils.py
Reverts CybercentreCanada/assemblyline-base#24
=> Revert "AL-128: Replace StringTable where feasible"

assemblyline/odm/models/config.py, dev/core/docker-compose-sca-upd.yml, dev/core/docker-compose.yml, dev/services/docker-compose.yml
Add the option for core containers to touch a file on a regular basis so we can see if they are frozen or deadlocked.
This is the less interesting counterpart to a matching PR in core.
=> Health checks

assemblyline/remote/datatypes/queues/priority.py, test/test_remote_datatypes.py
Have dispatcher track the queue value rather than the time placed in queue.
=> Dispatcher queue fix

assemblyline/odm/models/config.py, assemblyline/odm/models/user_settings.py
This patch adds fields to the model so the old UI can redirect to the new UI
=> Allow the current UI to recognize and interact with the new UI

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Changes to the odm for [Add proxy support to signature updater](https://cccs.atlassian.net/browse/AL-939)
Changes to the UI are in this PR: https://github.com/CybercentreCanada/assemblyline-ui/pull/38
=> Add proxy support in signature updater

assemblyline/common/constants.py, assemblyline/common/identify.py
added new type to support changes to extract regarding password protected office files 
https://github.com/CybercentreCanada/assemblyline-service-extract/pull/3
=> Added new type to support changes to extract

assemblyline/datastore/helper.py
Test for this bug are in the core repo
=> Fix error in ingester

assemblyline/odm/models/heuristic.py, assemblyline/odm/models/result.py
Change attack_id from Enum to Keyword in ODM model for heuristics and results
=> remove validation against attack id list

assemblyline/common/identify.py, setup.py
added a check to identify encrypted office files prior to sending to extract + added msoffcrypto module to setup.py
=> added check in identify for encrypted office files

assemblyline/odm/messages/submission.py
Adjust message types and create a helper method to support corresponding changes in core and ui
=> Submission lifecycle pubsub events

assemblyline/common/classification.yml
Reverts CybercentreCanada/assemblyline-base#79
=> Revert "Hotfix/classification"

assemblyline/common/classification.yml
Reverts CybercentreCanada/assemblyline-base#78
=> Revert "Use long version of the classification"

assemblyline/datastore/support/elasticsearch/build.py, assemblyline/odm/base.py, assemblyline/odm/models/tagging.py, assemblyline/odm/randomizer.py
Closes https://cccs.atlassian.net/browse/AL-752
=> Adding Operating System tag with validation in ODM

assemblyline/common/identify.py
tests passed, and functionality was verified in `dev`
=> Work around for msoffcrypto failure

assemblyline/common/identify.py
~~needs to be rebased once https://github.com/CybercentreCanada/assemblyline-base/pull/91 gets merged since this branch was based off of that PR's branch~~
tests passed in dev, ready to merge!
=> Regex tweak

assemblyline/common/forge.py, assemblyline/datastore/__init__.py, assemblyline/datastore/helper.py, assemblyline/datastore/stores/es_store.py, assemblyline/odm/base.py, assemblyline/odm/models/heuristic.py, assemblyline/odm/models/signature.py, assemblyline/odm/models/statistics.py, assemblyline/odm/models/tagging.py, assemblyline/odm/random_data/__init__.py, assemblyline/odm/random_data/create_test_data.py, assemblyline/odm/randomizer.py
When min count is set to 0, this will actually return the zero valued gaps.
=> Change way statistics are created 

assemblyline/odm/models/config.py
Confirmed to be working in LS Rancher
=> Pass additional labels k8s

dev/core/docker-compose.yml, docker/nginx-ssl-frontend/Dockerfile
Load latest ui-frontend container in dev core compose
=> Fix nginx-ssl-frontend container

assemblyline/common/comms.py
=> feature/next_only (dev)

assemblyline/common/classification.py, assemblyline/common/classification.yml, test/test_common.py
Allow dynamic classification in the classification engine
=> feature/dynamic_classification (dev)

assemblyline/common/str_utils.py, test/test_str_utils.py
=> hotfix/str_utils (dev)

assemblyline/odm/models/config.py
Added configuration for extended apikeys
=> feature/extended_apikeys (dev)

assemblyline/datastore/stores/es_store.py
Use asynchronous reindexing so it doesn't timeout
=> hotfix/reindex (dev)

assemblyline/common/identify.py
Reverts CybercentreCanada/assemblyline-base#196
=> Revert "Hotfix/identify sendmail emails (dev)"

assemblyline/odm/models/config.py
=> feature/max_dtl (dev)

assemblyline/datastore/stores/es_store.py
Allow replicas and shards to be set from ENV
=> feature/ILM_shards (dev)

assemblyline/common/logformat.py
Change json logs to be ECS compliant
=> hotfix/json_logs_ecs (dev)

assemblyline/datastore/support/elasticsearch/build.py
Fix nested fields to behave properly
=> hotfix/nested (dev)

assemblyline/datastore/stores/es_store.py
Make index copy operation safer by monitoring target status.
=> hotfix/safer_index_commands (dev)

assemblyline/common/constants.py, assemblyline/common/identify.py
=> Add sysmon identify

assemblyline/datastore/stores/es_store.py, assemblyline/datastore/support/elasticsearch/build.py, assemblyline/datastore/support/elasticsearch/schemas.py
Let nested field be guessed using the first value and enforce strings as keywords
=> hotfix/nested_guessing (dev)

assemblyline/common/constants.py, assemblyline/common/identify.py
=> Add outlook emails to identify

assemblyline/common/identify.py
closes https://cccs.atlassian.net/browse/AL-1217
=> Adding strong indicator for code/ps1

assemblyline/common/identify.py
Closes https://cccs.atlassian.net/browse/AL-1219
=> Adding strong indicators for vbs identification

setup.py, test/requirements.txt, test/test_identify.py
closes https://cccs.atlassian.net/browse/AL-319
=> Adding testing suite for identify

assemblyline/common/custom.magic, assemblyline/common/identify.py, assemblyline/datastore/helper.py, setup.py, test/requirements.txt, test/test_identify.py
Detection based on MS-ONESTORE header GUID for .one files
=> Add OneNote file detection to custom magic (dev)

assemblyline/odm/models/tagging.py
DEV PR for https://cccs.atlassian.net/browse/AL-760
=> Adding dynamic shortcut tag

assemblyline/common/constants.py, assemblyline/common/custom.magic, assemblyline/common/identify.py
Tested on staging, allows extract to run on OneNote files.
=> Add OneNote detection to identify

assemblyline/common/identify.py, test/test_identify.py
https://cccs.atlassian.net/browse/AL-1245
build and test passed in dev
=> Fixing bugs in regular expressions and code logic

assemblyline/common/identify.py, test/test_identify.py
Closes https://cccs.atlassian.net/browse/AL-1273
=> Adding better PowerShell identification

assemblyline/common/backupmanager.py
Closes: https://github.com/CybercentreCanada/assemblyline-base/issues/319
=> hotfix exception typo

assemblyline/common/identify.py
Addressing identification issue with https://cccs.atlassian.net/browse/AL-1047
=> Adding more commandlets to assist with identification

setup.py
Changes will be have to made to core to flip the requirement to ">=18" as the import would change.
=> Use version 17 as latest for now

assemblyline/common/identify.py
Closes https://cccs.atlassian.net/browse/AL-1351
=> Adding strong indicator for ps1

assemblyline/common/identify.py, test/test_identify.py
Closes #325 
Thank you for your help @malvidin and @cccs-rs !
=> Debian Buster patch for correctly identifying pcaps

assemblyline/common/identify.py, test/test_identify.py
Closes https://cccs.atlassian.net/browse/AL-1366
=> Adding strong indicators for vbs

assemblyline/common/constants.py, assemblyline/common/identify.py, test/test_identify.py
Reverts CybercentreCanada/assemblyline-base#348
=> Revert "Mo"

assemblyline/common/constants.py, assemblyline/common/identify.py, test/test_identify.py
Closes https://cccs.atlassian.net/browse/AL-1367
=> Adding resource/mo as file type

assemblyline/common/identify.py, test/test_identify.py
Closes https://cccs.atlassian.net/browse/AL-1398
=> Adding special Word case for magic labels generated

assemblyline/common/identify.py, test/test_identify.py
Closes https://cccs.atlassian.net/browse/AL-1411
=> Adding more strong indicators for PS1

assemblyline/common/compat_tag_map.py, assemblyline/odm/models/tagging.py
Adding the vector tag to be used in the newer version of APIVector
=> Adding the vector tag

assemblyline/common/identify.py, test/test_identify.py
Addresses https://cccs.atlassian.net/browse/AL-1478
=> Improving javascript dump identification

assemblyline/odm/models/config.py, assemblyline/odm/models/service.py
Closes: https://cccs.atlassian.net/browse/AL-1498
=> Global Registry Type for Services

Dockerfile, README.md, docker/al_dev/Dockerfile, docker/al_management/Dockerfile, docker/local_dev.Dockerfile, pipelines/azure-tests.yaml, setup.py
Reverts CybercentreCanada/assemblyline-base#519
=> Revert "Python 3.10 bullseye upgrade (dev)"

assemblyline/common/identify.py, test/test_identify.py
Closes: https://github.com/CybercentreCanada/assemblyline-service-emlparser/issues/29
=> change Content-Type to a weak indicator

assemblyline/remote/datatypes/hash.py, assemblyline/remote/datatypes/queues/named.py, assemblyline/remote/datatypes/set.py
This will reduce the number of calls to Redis EXPIRE function by only calling it if the last time we've called it is more then half the total requested TTL.
=> Added conditional expire functions to redis structures

dev/core/docker-compose-sca-upd.yml
Fixes issues when using updater & scaler in development, mimics the docker-compose appliance values (where applicable).
=> fix dev when using scaler/updater

assemblyline/common/dict_utils.py
Added functions to get a predictive list of sorted tuples from a dictionary
=> dict fingerprint

assemblyline/datastore/support/elasticsearch/build.py, assemblyline/odm/base.py, assemblyline/odm/randomizer.py
FlattenedObject should use a JSON encoder so we can reverse the operation
=> JSON Meta 

assemblyline/odm/models/tagging.py
Added FileShortcut and reordered the elements in File alphabetically.
=> [dev] Adding tags for shortcut files

assemblyline/common/identify.py, test/test_identify.py
Addresses https://cccs.atlassian.net/browse/AL-1708
=> Adding strong indicators for  Powershell

assemblyline/filestore/__init__.py
In response to: https://discord.com/channels/908084610158714900/908717528082173983/965582563278204948
=> Add support for IAM-based S3 access to filestore

assemblyline/common/net.py, test/test_net.py
return False when ip part value is outside of 0 - 255 instead of
continuing
=> fix ip part value check in is_valid_ip (dev)

assemblyline/common/net.py, test/test_net.py
return False when ip part value is outside of 0 - 255 instead of
continuing
=> fix ip part value check in is_valid_ip

assemblyline/common/custom.yara
Adding rem and set command checks for batch identification through YARA.
=> [master] Improving batch detection

assemblyline/common/lucene.lark, assemblyline/common/postprocess.py, assemblyline/datastore/helper.py, assemblyline/odm/__init__.py, assemblyline/odm/models/actions.py, setup.py, test/test_postprocess.py, test/test_submission_filter.py
WRT: CybercentreCanada/assemblyline-core#573
=> Heuristic loading (dev)

assemblyline/datastore/helper.py
WRT: CybercentreCanada/assemblyline-core#573
=> heuristic loading

assemblyline/common/isotime.py
Partially addresses https://cccs.atlassian.net/browse/AL-1859
=> Adding min/max, formatting functions

assemblyline/common/net.py, assemblyline/odm/base.py
Expanded the domain Unicode to `sys.maxunicode`
=> Broaden Unicode range for domains

assemblyline/common/net.py, assemblyline/odm/base.py
Continues: https://github.com/CybercentreCanada/assemblyline-base/pull/811
=> Broader domains

assemblyline/odm/models/ontology/ontology.py, assemblyline/odm/models/ontology/results/malware_config.py
https://github.com/CybercentreCanada/Maco/blob/b653f268a5f874db1e8ec2e0834e9b40f7461ac6/maco/model.py#L192
=> fix sleep_delay to match MACO model

assemblyline/common/identify_defaults.py
Required for https://github.com/CybercentreCanada/assemblyline-service-cape/pull/79
=> Adding extensions for archives

assemblyline/common/identify_defaults.py
Required to add ZIP support to CAPE
=> Adding zip extension to map

assemblyline/common/identify.py, assemblyline/datastore/collection.py, assemblyline/odm/randomizer.py, dev/services/docker-compose.yml
- Added support to return seq_no and primary_term during search
- Allow multi-key sorting
=> Seq No and Primary Term (dev)

assemblyline/datastore/collection.py
- Added support to return seq_no and primary_term during search
- Allow multi-key sorting
=> Seq No and Primary Term

test/test_regexes.py
For https://github.com/CybercentreCanada/assemblyline-base/pull/927#pullrequestreview-1141230841
=> Adding tests for FULL_URI

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Aids with undoing specific credentials per service and utilizing system settings or removing authentication altogether if not necessary.
=> Allow registry credentials to be cleared or empty

assemblyline/common/hexdump.py
- Used for decoding hex strings to bytes
=> Adding the unhexlify utility

assemblyline/odm/models/result.py
Addresses: https://cccs.atlassian.net/browse/AL-2058
=> Add a file property for bypassing Dynamic Recursion Prevention

assemblyline/odm/models/replay.py
Related: https://cccs.atlassian.net/browse/AL-2077
=> Add a sync check for Replay loader

assemblyline/common/identify_defaults.py
Partially addresses https://cccs.atlassian.net/browse/AL-2063
=> Adding a code/shell -> .sh mapping

assemblyline/common/identify_defaults.py
Partially addressing https://cccs.atlassian.net/browse/AL-1966
=> Adding rar extension

assemblyline/common/identify_defaults.py
Partially addresses https://cccs.atlassian.net/browse/AL-1966?focusedCommentId=126406
=> Adding the trusted mime for registry files

assemblyline/common/identify_defaults.py
Addresses https://cccs.atlassian.net/browse/AL-1966?focusedCommentId=126426
=> Adding VBE tag map

assemblyline/common/custom.yara
Partially addresses https://cccs.atlassian.net/browse/AL-2114
=> Improving JScript identification

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2236
=> PowerShell most likely does not contain a 'powershell' command in it

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2259
=> Adding -uri arg to ps1 regex

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2275
Overwrites https://github.com/CybercentreCanada/assemblyline-base/pull/1065
=> Adding weak VBS id regex

assemblyline/common/custom.yara
Complementing https://github.com/CybercentreCanada/assemblyline-base/commit/3a032f11694b3f58fb2b5cca1ab38686a076507a
=> Use both ps1 for batch

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2253
=> Adding more commands and argument flags to ps1 identification regexes

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2300
=> -OutF is also a valid arg for IWR

assemblyline/odm/base.py, assemblyline/odm/models/config.py, assemblyline/odm/models/result.py
Addresses:
- [Fetchers need an optional proxy](https://github.com/orgs/CybercentreCanada/projects/11?pane=issue&itemId=21671237)
- [Typing affecting tests for services](https://github.com/orgs/CybercentreCanada/projects/11?pane=issue&itemId=21671178) (Sigma)
- Bug in ODM → Markdown that displays `[]` as the default for non-list fields
- Adds a uniform container configuration for performing service installation/updates
=> Assorted bugfixes

assemblyline/odm/models/config.py
Closes: https://cccs.atlassian.net/browse/AL-2311
=> Configure default User-Agent header for submissions

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2316
Uses this file as the guideline https://github.com/CybercentreCanada/assemblyline-unittest-samples/commit/0e82722fb3137a9a418c3b8607a5b9bbe3670108
=> Handling js with octet stream mime, adding word boundaries on ps1 cmds

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2406
=> Refactoring python ID yara rule, adding high confidence rule

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2440
=> Tweaking ps1 ID rule and batch ID regex

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2458
=> Fix up ActiveXObject regex in code/javascript rule

assemblyline/odm/models/result.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/68
=> Add optional `body_config` field to ResultSection objects

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/16
=> Add a `classification` to the Service(Delta) models

.gitignore, .vscode/settings.json, assemblyline/common/isotime.py, test/test_common.py, test/test_isotime.py
- Also added VSCode stylings standard
=> Adding LOCAL_FMT_WITH_MS

assemblyline/common/heuristics.py, external/generate_attack_map.py
Closes: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-2163
=> Ensure software identified as malware (not tool) is attributed as implants

assemblyline/odm/models/ontology/ontology.py, assemblyline/odm/models/ontology/results/signature.py
Closes: https://cccs.atlassian.net/browse/AL-2546
=> Add `signature_id` field to Signature ont.

assemblyline/common/identify_defaults.py
Partially addresses https://cccs.atlassian.net/browse/AL-2532
=> Adding 7-zip extension in identify_defaults

assemblyline/datastore/collection.py, test/test_datastore.py
To be able to page through list of IDs without knowing if the IDs still exist
=> Added multiget_search function

assemblyline/common/postprocess.py
Keep track of the extended_scan state better and make sure the alert message is sent before trigerring a resubmit.
=> Alert Hotfix

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Related to: https://cccs.atlassian.net/browse/AL-2544?focusedCommentId=147492
=> Add configuration option for syncing signatures with source

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2612, https://cccs.atlassian.net/browse/AL-2613
=> Fixing identification of powershell scripts that call themselves

assemblyline/odm/models/ontology/results/malware_config.py
Relates to: https://github.com/CybercentreCanada/Maco/pull/24
=> Update to support a list of encryption per binary

assemblyline/common/identify_defaults.py
Starting point for CybercentreCanada/assemblyline/issues/104
=> Identify zstd archives

assemblyline/datastore/collection.py, test/test_datastore.py
Modified multiget_search() to include query, filters and access control parameters.
=> Multi Get Search (Master): added more query parameters

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-2695
=> Adding code/au3 identification

assemblyline/common/custom.yara
Partially addressing https://cccs.atlassian.net/browse/AL-2697
=> Tweaking ps1 and js identification rules

assemblyline/common/identify_defaults.py
Partially addressing https://cccs.atlassian.net/browse/AL-2718
=> Adding trusted mime and magic patterns for video/asf files

assemblyline/common/custom.yara, assemblyline/common/identify_defaults.py
Addresses https://github.com/CybercentreCanada/assemblyline/issues/127
=> Tweaking identification of python and java files

assemblyline/datastore/collection.py, test/test_datastore.py
Added the "size" and "include" property to the facet search.
=> Feature/Facet (dev)

assemblyline/common/str_utils.py, assemblyline/odm/models/result.py
Partially addresses https://cccs.atlassian.net/browse/AL-2679
=> Adding method to StringTable to get keys

assemblyline/odm/models/result.py
=> Adding comments pointing to duplicated code that cannot be changed du… [dev]

assemblyline/datastore/collection.py, test/test_datastore.py
Added the "size" and "include" property to the facet search.
=> Feature/Facet (master)

assemblyline/common/custom.yara, assemblyline/common/identify_defaults.py
Karton's Script Identification:
VBS: 
https://github.com/CERT-Polska/karton-classifier/blob/4cf125296e3a0c1d6c1cb8c16f97d608054c7f19/karton/classifier/classifier.py#L650
JS:
https://github.com/CERT-Polska/karton-classifier/blob/4cf125296e3a0c1d6c1cb8c16f97d608054c7f19/karton/classifier/classifier.py#L659
PS1: 
https://github.com/CERT-Polska/karton-classifier/blob/4cf125296e3a0c1d6c1cb8c16f97d608054c7f19/karton/classifier/classifier.py#L671
Other:
Karton: Additional strings for identifying compiled autoIT scripts
https://github.com/CERT-Polska/karton-autoit-ripper/blob/master/karton/autoit_ripper/autoit.yar 
https://github.com/CybercentreCanada/assemblyline-base/blob/8eda11b6ccd48fdeeaaca9b3bbbe95e7c2829e01/assemblyline/common/custom.yara#L1072
From CAPE's Sflock:
Possible trusted mimes: …
=> Identify Improvements

assemblyline/common/str_utils.py, setup.py
https://peps.python.org/pep-0561/
=> Add py.typed to allow mypy to recognize inline type hints

assemblyline/odm/models/ontology/ontology.py, assemblyline/odm/models/ontology/results/malware_config.py, assemblyline/odm/models/ontology/results/network.py
Related to: https://github.com/CybercentreCanada/Maco/pull/35
=> Update DNS model in MalwareConfig to match MACO

assemblyline/common/custom.yara
Needed to identify 161078c53263fc1893f38b94e6c11441b61a120031f553d25d90cac7ecdb1ae6 as code/ps1 instead of code/batch
=> Adding detection for ps1 on first line

.vscode/settings.json, assemblyline/odm/base.py, test/test_regexes.py
Fixes the @ in path problem of https://github.com/CybercentreCanada/assemblyline/issues/165. We did accept @ in path already but it was breaking the host capture group.
=> Uri regex fix

assemblyline/odm/models/tagging.py
Related to:
- https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-2810
- https://github.com/CybercentreCanada/assemblyline-service-espresso/pull/22
=> ('24) Add tag for imported packages in JAR files

assemblyline/datastore/store.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/167
=> Remove unnecessary connection resets to the datastore

assemblyline/odm/models/replay.py, assemblyline/odm/models/workflow.py, assemblyline/odm/random_data/__init__.py, assemblyline/odm/random_data/create_test_data.py, dev/core/docker-compose-sca-upd.yml, dev/core/docker-compose.yml
Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-1988
=> Add an enabled state to workflows

assemblyline/common/identify_defaults.py
Identification for CybercentreCanada/assemblyline/issues/203
=> Identify epub documents

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
CybercentreCanada/assemblyline-ui-frontend/pull/984
CybercentreCanada/assemblyline-core/pull/905
=> Add labeling to service containers (dev)

assemblyline/common/caching.py, assemblyline/datastore/collection.py, assemblyline/datastore/helper.py
CybercentreCanada/assemblyline-core/pull/903
CybercentreCanada/assemblyline-ui/pull/868
=> Metadata validate

assemblyline/odm/models/config.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/200
=> Add a `token_server` registry configuration to support token-based auth flows

assemblyline/odm/models/alert.py, assemblyline/odm/random_data/__init__.py
Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-2975
=> Update Alert events to track removed labels

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Reverts CybercentreCanada/assemblyline-base#1229
=> Revert feature (Windows support)

assemblyline/common/custom.yara
Closes https://cccs.atlassian.net/browse/AL-3016
=> Bugfix for JavaScript mis-identified as emails

assemblyline/filestore/transport/s3.py, assemblyline/odm/base.py, test/test_regexes.py
Reverts CybercentreCanada/assemblyline-base#1597
This feature introduced a breaking change that impacts other deployments in EKS. 
Ref: https://discord.com/channels/908084610158714900/1227352219431473263/1227730806299037717
=> Revert "S3 IAM role based access - Dev Branch"

assemblyline/filestore/transport/s3.py
Reverts CybercentreCanada/assemblyline-base#1597
This feature introduced a breaking change that impacts other deployments in EKS. 
Ref: https://discord.com/channels/908084610158714900/1227352219431473263/1227730806299037717
=> Revert "S3 IAM role based access"

assemblyline/odm/models/ontology/ontology.py, assemblyline/odm/models/ontology/results/network.py, assemblyline/odm/models/ontology/results/signature.py
Related to: https://cccs.atlassian.net/browse/AL-3093
=> Add classfication to Signature objects in Ontology

assemblyline/odm/models/config.py
Allow the OAuth provider to set its encryption algorythm use for JWT token signing verification
=> JWT Security

assemblyline/odm/models/config.py
Related to:
- https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-2909
- https://github.com/CybercentreCanada/assemblyline/issues/111
- https://github.com/CybercentreCanada/assemblyline/issues/168
=> Add configuration to extend submit by SHA256 functionality

assemblyline/odm/models/config.py
Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-3082
=> Create configuration to always generate a submission, even on cache hit

assemblyline/odm/models/replay.py
Related to: https://cccs.atlassian.net/browse/AL-2925
=> Add configuration for syncing signatures

assemblyline/odm/base.py, assemblyline/odm/models/tagging.py, assemblyline/odm/randomizer.py, setup.py
Based on: https://github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md
=> Add JA3S and JA4 fingerprinting to tagging

assemblyline/common/identify.py, assemblyline/common/identify_defaults.py
Addresses https://cccs.atlassian.net/browse/AL-3220
=> Re-ordering trusted magic labels, adding support from other projects

assemblyline/datastore/helper.py, assemblyline/odm/models/config.py
Added a param to oauth to pass in the secret while authenticating the user
=> Hotfix Auth

assemblyline/common/custom.yara
Adding some new indicator to cover a different python script from CybercentreCanada/assemblyline/issues/238.
=> Added two requests and socket functions to identify python files

assemblyline/cachestore/__init__.py, assemblyline/common/archiving.py, assemblyline/common/forge.py, assemblyline/datastore/helper.py, assemblyline/filestore/__init__.py, assemblyline/filestore/transport/azure.py, assemblyline/odm/models/config.py, setup.py
Allow auth using an MI with FileStore
=> Allow auth without secrets - File Store Changes

assemblyline/common/isotime.py
See https://github.com/CybercentreCanada/assemblyline-core/pull/1003
=> Fix ttl and expiry time comparison

assemblyline/common/classification.yml
Added is_hidden as a possible field for the classification engine
=> Hidden Classification Markings

assemblyline/odm/models/ontology/ontology.py
Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-3333
=> Add a field as a catch-all for unstructured data (ie. logs)

assemblyline/datastore/helper.py, dev/core/docker-compose.yml
Resolves: https://github.com/CybercentreCanada/assemblyline/issues/212
=> Limit `save_or_freshen_file` usage to HOT index

assemblyline/odm/models/config.py
Reverts CybercentreCanada/assemblyline-base#1755
=> Revert "Federated Identity Credentials Dev"

assemblyline/odm/models/config.py
Add a flag in the config to move success and failure logs to the audit logs
=> Audit Login (dev)

assemblyline/odm/models/config.py
Add params to file source to select specific service and to skip the download from url call
=> URL to Specific Service (dev)

assemblyline/odm/models/config.py
Add params to file source to select specific service and to skip the download from url call
=> URL to Specific Service

assemblyline/odm/models/config.py
Added the public key in the APIProxies that contains properties to be passed to the frontend for configuration purposes.
=> Update/Borealis (master)

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Relates to:
- https://cccs.atlassian.net/browse/AL-3247
- https://github.com/CybercentreCanada/assemblyline/issues/136
- https://github.com/CybercentreCanada/assemblyline/issues/159
- https://github.com/CybercentreCanada/assemblyline/issues/248
=> Add new configuration options for UpdateSource model

assemblyline/odm/models/config.py
Dev branch PR corresponding to CybercentreCanada/assemblyline-base/pull/1877
=> feat: add enable_pod_security flag for scaler

assemblyline/datastore/helper.py
The save_or_freshen_file code is likely overwriting the access type flags. Make sure they are merged rather than overwritten.
CybercentreCanada/assemblyline/issues/312
=> make sure the file access tags are OR updated

assemblyline/common/custom.yara
Needs to be merged at the same time as https://github.com/CybercentreCanada/assemblyline-unittest-samples/pull/45 for tests to line up
=> Identify powershell invocation as code/ps1

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/248
=> Add a field for setting data for POST requests

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/309
=> Add a default pattern to UpdateConfig

assemblyline/odm/models/config.py
Related to: https://cccs.atlassian.net/jira/software/c/projects/AL/issues/AL-3500
=> Add examples of more file sources that are open source

assemblyline/odm/models/config.py
Changed the "editable_params" to "restricted_params" flipping the logic around. Added the list of excluded services to the profiles which prevents limited users from making changes to those.
=> Feature/SubmissionProfiles (dev)

assemblyline/odm/models/tagging.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/336
=> Add technique.exploit tag

assemblyline/common/isotime.py, assemblyline/datastore/helper.py, assemblyline/odm/models/apikey.py, assemblyline/odm/models/config.py, assemblyline/odm/models/user.py, assemblyline/odm/random_data/__init__.py, assemblyline/odm/randomizer.py
Separate data model of Apikey from User.
Add more data to store in apikeys
=> Separate data model of Apikey from User

assemblyline/odm/base.py, assemblyline/odm/messages/task.py, assemblyline/odm/models/config.py, assemblyline/odm/models/submission.py, assemblyline/odm/models/user_settings.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/332
=> Cleanup deprecated fields from 4.5

assemblyline/odm/models/submission.py
CybercentreCanada/assemblyline-core/pull/1070
=> add dispatcher tracing events (dev)

assemblyline/odm/models/service.py, assemblyline/odm/models/service_delta.py
added new key for using managed identity for authenticating ado git repositories
=> added new key for using managed identity for authenticating ado git repositories

assemblyline/odm/models/submission.py
CybercentreCanada/assemblyline-core/pull/1070
=> add dispatcher tracing events

assemblyline/common/identify_defaults.py
=> Add identify_default for squashfs

assemblyline/run/cli.py
…unctionality following changes to the API
=> Revert changes to session management using the CLI back to original f… (dev)
